on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v2

        -   name: Deploy to EC2
            run: |
                echo "${{secrets.SSH_KEY }}" > ~/.ssh/key.pem
                ssh -i "~/.ssh/key.pem" ubuntu@ec2-13-53-187-164.eu-north-1.compute.amazonaws.com
                
            