on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v2
        
        - name: print out example job
          uses: appleboy/ssh-action@v0.1.10
          with:
              host: ec2-13-53-187-164.eu-north-1.compute.amazonaws.com
              username: ubuntu
              key: ${{ secrets.SSH_KEY }}
              port: 22
              command_timeout: 30m
              script: | 
                echo "Nice Job!!!"
                ls / 
                cd /var/www/vhosts/tumbleweedandtwang.com
                git pull