on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v2

        -   name: Deploy to EC2
            run: |
                