on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout
            uses: actions/checkout@v2
        
        - name: Install SSH key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH_KEY }}
            name: id_rsa # optional
            known_hosts: ${{ secrets.KNOWN_HOSTS }}
            config: ${{ secrets.CONFIG }} # ssh_config; optional
            if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
        
        -   name: Deploy to EC2
        
            run: |
                ssh -i "~/.ssh/id_rsa" ubuntu@ec2-13-53-187-164.eu-north-1.compute.amazonaws.com
                
            